spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TESTDB;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Log file location
logging.file.name=logs/cardsit.log

# Log level
logging.level.root=INFO

# Optional (better readability)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n